/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root"
import { Route as HomeRouteImport } from "./../routes/_home"
import { Route as HomeIndexRouteImport } from "./../routes/_home.index"
import { Route as HomeTermsOfServiceRouteImport } from "./../routes/_home.terms-of-service"
import { Route as HomePrivacyPolicyRouteImport } from "./../routes/_home.privacy-policy"

const HomeRoute = HomeRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./../routes/_home.lazy").then((d) => d.Route))
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRoute,
} as any)
const HomeTermsOfServiceRoute = HomeTermsOfServiceRouteImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import("./../routes/_home.terms-of-service.lazy").then((d) => d.Route),
)
const HomePrivacyPolicyRoute = HomePrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import("./../routes/_home.privacy-policy.lazy").then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute
  "/privacy-policy": typeof HomePrivacyPolicyRoute
  "/terms-of-service": typeof HomeTermsOfServiceRoute
}
export interface FileRoutesByTo {
  "/privacy-policy": typeof HomePrivacyPolicyRoute
  "/terms-of-service": typeof HomeTermsOfServiceRoute
  "/": typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_home": typeof HomeRouteWithChildren
  "/_home/privacy-policy": typeof HomePrivacyPolicyRoute
  "/_home/terms-of-service": typeof HomeTermsOfServiceRoute
  "/_home/": typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/privacy-policy" | "/terms-of-service"
  fileRoutesByTo: FileRoutesByTo
  to: "/privacy-policy" | "/terms-of-service" | "/"
  id:
    | "__root__"
    | "/_home"
    | "/_home/privacy-policy"
    | "/_home/terms-of-service"
    | "/_home/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_home": {
      id: "/_home"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_home/": {
      id: "/_home/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    "/_home/terms-of-service": {
      id: "/_home/terms-of-service"
      path: "/terms-of-service"
      fullPath: "/terms-of-service"
      preLoaderRoute: typeof HomeTermsOfServiceRouteImport
      parentRoute: typeof HomeRoute
    }
    "/_home/privacy-policy": {
      id: "/_home/privacy-policy"
      path: "/privacy-policy"
      fullPath: "/privacy-policy"
      preLoaderRoute: typeof HomePrivacyPolicyRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomePrivacyPolicyRoute: typeof HomePrivacyPolicyRoute
  HomeTermsOfServiceRoute: typeof HomeTermsOfServiceRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomePrivacyPolicyRoute: HomePrivacyPolicyRoute,
  HomeTermsOfServiceRoute: HomeTermsOfServiceRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
